version: '3.7'

services: 
  app:
    container_name: quran-backend
    depends_on: 
      - db
    build: 
      context: .
      dockerfile: Dockerfile
      target: local
    environment: 
      DEBUG: "true"
      SERVING_PORT: ":8080"
      DB_HOST: quran_backend_db
    volumes: 
      - .:/app
    working_dir: /app
    env_file: 
      - .env
    ports: 
      - 8080:8080
    command: make watch
    tty: true
    networks: 
      - quran_backend
  
  db:
    image: postgres:11
    container_name: quran_backend_db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: golang_example_db_test
      POSTGRES_PORT: 5433
    ports: 
      - 5432:5432
    networks: 
      - quran_backend
  
networks: 
  quran_backend: